// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.BeneficiaryIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BeneficiaryIntegrationTest_Roo_Configurable {
    
    declare @type: BeneficiaryIntegrationTest: @Configurable;
    
}
