// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.BeneficiaryItemChoiceDataOnDemand;
import com.howed.heirshare5.domain.BeneficiaryItemChoiceIntegrationTest;
import com.howed.heirshare5.repository.BeneficiaryItemChoiceRepository;
import com.howed.heirshare5.service.BeneficiaryItemChoiceService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BeneficiaryItemChoiceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BeneficiaryItemChoiceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BeneficiaryItemChoiceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BeneficiaryItemChoiceIntegrationTest: @Transactional;
    
    @Autowired
    BeneficiaryItemChoiceDataOnDemand BeneficiaryItemChoiceIntegrationTest.dod;
    
    @Autowired
    BeneficiaryItemChoiceService BeneficiaryItemChoiceIntegrationTest.beneficiaryItemChoiceService;
    
    @Autowired
    BeneficiaryItemChoiceRepository BeneficiaryItemChoiceIntegrationTest.beneficiaryItemChoiceRepository;
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testCountAllBeneficiaryItemChoices() {
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", dod.getRandomBeneficiaryItemChoice());
        long count = beneficiaryItemChoiceService.countAllBeneficiaryItemChoices();
        Assert.assertTrue("Counter for 'BeneficiaryItemChoice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testFindBeneficiaryItemChoice() {
        BeneficiaryItemChoice obj = dod.getRandomBeneficiaryItemChoice();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to provide an identifier", id);
        obj = beneficiaryItemChoiceService.findBeneficiaryItemChoice(id);
        Assert.assertNotNull("Find method for 'BeneficiaryItemChoice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BeneficiaryItemChoice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testFindAllBeneficiaryItemChoices() {
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", dod.getRandomBeneficiaryItemChoice());
        long count = beneficiaryItemChoiceService.countAllBeneficiaryItemChoices();
        Assert.assertTrue("Too expensive to perform a find all test for 'BeneficiaryItemChoice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BeneficiaryItemChoice> result = beneficiaryItemChoiceService.findAllBeneficiaryItemChoices();
        Assert.assertNotNull("Find all method for 'BeneficiaryItemChoice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BeneficiaryItemChoice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testFindBeneficiaryItemChoiceEntries() {
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", dod.getRandomBeneficiaryItemChoice());
        long count = beneficiaryItemChoiceService.countAllBeneficiaryItemChoices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BeneficiaryItemChoice> result = beneficiaryItemChoiceService.findBeneficiaryItemChoiceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BeneficiaryItemChoice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BeneficiaryItemChoice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testFlush() {
        BeneficiaryItemChoice obj = dod.getRandomBeneficiaryItemChoice();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to provide an identifier", id);
        obj = beneficiaryItemChoiceService.findBeneficiaryItemChoice(id);
        Assert.assertNotNull("Find method for 'BeneficiaryItemChoice' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBeneficiaryItemChoice(obj);
        Integer currentVersion = obj.getVersion();
        beneficiaryItemChoiceRepository.flush();
        Assert.assertTrue("Version for 'BeneficiaryItemChoice' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testUpdateBeneficiaryItemChoiceUpdate() {
        BeneficiaryItemChoice obj = dod.getRandomBeneficiaryItemChoice();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to provide an identifier", id);
        obj = beneficiaryItemChoiceService.findBeneficiaryItemChoice(id);
        boolean modified =  dod.modifyBeneficiaryItemChoice(obj);
        Integer currentVersion = obj.getVersion();
        BeneficiaryItemChoice merged = beneficiaryItemChoiceService.updateBeneficiaryItemChoice(obj);
        beneficiaryItemChoiceRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BeneficiaryItemChoice' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testSaveBeneficiaryItemChoice() {
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", dod.getRandomBeneficiaryItemChoice());
        BeneficiaryItemChoice obj = dod.getNewTransientBeneficiaryItemChoice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BeneficiaryItemChoice' identifier to be null", obj.getId());
        try {
            beneficiaryItemChoiceService.saveBeneficiaryItemChoice(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        beneficiaryItemChoiceRepository.flush();
        Assert.assertNotNull("Expected 'BeneficiaryItemChoice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BeneficiaryItemChoiceIntegrationTest.testDeleteBeneficiaryItemChoice() {
        BeneficiaryItemChoice obj = dod.getRandomBeneficiaryItemChoice();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BeneficiaryItemChoice' failed to provide an identifier", id);
        obj = beneficiaryItemChoiceService.findBeneficiaryItemChoice(id);
        beneficiaryItemChoiceService.deleteBeneficiaryItemChoice(obj);
        beneficiaryItemChoiceRepository.flush();
        Assert.assertNull("Failed to remove 'BeneficiaryItemChoice' with identifier '" + id + "'", beneficiaryItemChoiceService.findBeneficiaryItemChoice(id));
    }
    
}
