// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.Estate;
import com.howed.heirshare5.domain.EstateAdministrator;
import com.howed.heirshare5.domain.EstateAdministratorDataOnDemand;
import com.howed.heirshare5.domain.EstateDataOnDemand;
import com.howed.heirshare5.repository.EstateRepository;
import com.howed.heirshare5.service.EstateService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EstateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EstateDataOnDemand: @Component;
    
    private Random EstateDataOnDemand.rnd = new SecureRandom();
    
    private List<Estate> EstateDataOnDemand.data;
    
    @Autowired
    EstateAdministratorDataOnDemand EstateDataOnDemand.estateAdministratorDataOnDemand;
    
    @Autowired
    EstateService EstateDataOnDemand.estateService;
    
    @Autowired
    EstateRepository EstateDataOnDemand.estateRepository;
    
    public Estate EstateDataOnDemand.getNewTransientEstate(int index) {
        Estate obj = new Estate();
        setEstateAdministrator(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void EstateDataOnDemand.setEstateAdministrator(Estate obj, int index) {
        EstateAdministrator estateAdministrator = estateAdministratorDataOnDemand.getRandomEstateAdministrator();
        obj.setEstateAdministrator(estateAdministrator);
    }
    
    public void EstateDataOnDemand.setTitle(Estate obj, int index) {
        String title = "title_" + index;
        if (title.length() > 30) {
            title = new Random().nextInt(10) + title.substring(1, 30);
        }
        obj.setTitle(title);
    }
    
    public Estate EstateDataOnDemand.getSpecificEstate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Estate obj = data.get(index);
        Long id = obj.getId();
        return estateService.findEstate(id);
    }
    
    public Estate EstateDataOnDemand.getRandomEstate() {
        init();
        Estate obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return estateService.findEstate(id);
    }
    
    public boolean EstateDataOnDemand.modifyEstate(Estate obj) {
        return false;
    }
    
    public void EstateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = estateService.findEstateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Estate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Estate>();
        for (int i = 0; i < 10; i++) {
            Estate obj = getNewTransientEstate(i);
            try {
                estateService.saveEstate(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            estateRepository.flush();
            data.add(obj);
        }
    }
    
}
