// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.EstateAdministratorDataOnDemand;
import com.howed.heirshare5.domain.EstateAdministratorIntegrationTest;
import com.howed.heirshare5.repository.EstateAdministratorRepository;
import com.howed.heirshare5.service.EstateAdministratorService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstateAdministratorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstateAdministratorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstateAdministratorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EstateAdministratorIntegrationTest: @Transactional;
    
    @Autowired
    EstateAdministratorDataOnDemand EstateAdministratorIntegrationTest.dod;
    
    @Autowired
    EstateAdministratorService EstateAdministratorIntegrationTest.estateAdministratorService;
    
    @Autowired
    EstateAdministratorRepository EstateAdministratorIntegrationTest.estateAdministratorRepository;
    
    @Test
    public void EstateAdministratorIntegrationTest.testCountAllEstateAdministrators() {
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", dod.getRandomEstateAdministrator());
        long count = estateAdministratorService.countAllEstateAdministrators();
        Assert.assertTrue("Counter for 'EstateAdministrator' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testFindEstateAdministrator() {
        EstateAdministrator obj = dod.getRandomEstateAdministrator();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to provide an identifier", id);
        obj = estateAdministratorService.findEstateAdministrator(id);
        Assert.assertNotNull("Find method for 'EstateAdministrator' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EstateAdministrator' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testFindAllEstateAdministrators() {
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", dod.getRandomEstateAdministrator());
        long count = estateAdministratorService.countAllEstateAdministrators();
        Assert.assertTrue("Too expensive to perform a find all test for 'EstateAdministrator', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EstateAdministrator> result = estateAdministratorService.findAllEstateAdministrators();
        Assert.assertNotNull("Find all method for 'EstateAdministrator' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EstateAdministrator' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testFindEstateAdministratorEntries() {
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", dod.getRandomEstateAdministrator());
        long count = estateAdministratorService.countAllEstateAdministrators();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EstateAdministrator> result = estateAdministratorService.findEstateAdministratorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EstateAdministrator' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EstateAdministrator' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testFlush() {
        EstateAdministrator obj = dod.getRandomEstateAdministrator();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to provide an identifier", id);
        obj = estateAdministratorService.findEstateAdministrator(id);
        Assert.assertNotNull("Find method for 'EstateAdministrator' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstateAdministrator(obj);
        Integer currentVersion = obj.getVersion();
        estateAdministratorRepository.flush();
        Assert.assertTrue("Version for 'EstateAdministrator' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testUpdateEstateAdministratorUpdate() {
        EstateAdministrator obj = dod.getRandomEstateAdministrator();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to provide an identifier", id);
        obj = estateAdministratorService.findEstateAdministrator(id);
        boolean modified =  dod.modifyEstateAdministrator(obj);
        Integer currentVersion = obj.getVersion();
        EstateAdministrator merged = estateAdministratorService.updateEstateAdministrator(obj);
        estateAdministratorRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EstateAdministrator' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testSaveEstateAdministrator() {
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", dod.getRandomEstateAdministrator());
        EstateAdministrator obj = dod.getNewTransientEstateAdministrator(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EstateAdministrator' identifier to be null", obj.getId());
        try {
            estateAdministratorService.saveEstateAdministrator(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        estateAdministratorRepository.flush();
        Assert.assertNotNull("Expected 'EstateAdministrator' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EstateAdministratorIntegrationTest.testDeleteEstateAdministrator() {
        EstateAdministrator obj = dod.getRandomEstateAdministrator();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstateAdministrator' failed to provide an identifier", id);
        obj = estateAdministratorService.findEstateAdministrator(id);
        estateAdministratorService.deleteEstateAdministrator(obj);
        estateAdministratorRepository.flush();
        Assert.assertNull("Failed to remove 'EstateAdministrator' with identifier '" + id + "'", estateAdministratorService.findEstateAdministrator(id));
    }
    
}
