// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.EstateDataOnDemand;
import com.howed.heirshare5.domain.EstateIntegrationTest;
import com.howed.heirshare5.repository.EstateRepository;
import com.howed.heirshare5.service.EstateService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EstateIntegrationTest: @Transactional;
    
    @Autowired
    EstateDataOnDemand EstateIntegrationTest.dod;
    
    @Autowired
    EstateService EstateIntegrationTest.estateService;
    
    @Autowired
    EstateRepository EstateIntegrationTest.estateRepository;
    
    @Test
    public void EstateIntegrationTest.testCountAllEstates() {
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", dod.getRandomEstate());
        long count = estateService.countAllEstates();
        Assert.assertTrue("Counter for 'Estate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstateIntegrationTest.testFindEstate() {
        Estate obj = dod.getRandomEstate();
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estate' failed to provide an identifier", id);
        obj = estateService.findEstate(id);
        Assert.assertNotNull("Find method for 'Estate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Estate' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EstateIntegrationTest.testFindAllEstates() {
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", dod.getRandomEstate());
        long count = estateService.countAllEstates();
        Assert.assertTrue("Too expensive to perform a find all test for 'Estate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Estate> result = estateService.findAllEstates();
        Assert.assertNotNull("Find all method for 'Estate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Estate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstateIntegrationTest.testFindEstateEntries() {
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", dod.getRandomEstate());
        long count = estateService.countAllEstates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Estate> result = estateService.findEstateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Estate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Estate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstateIntegrationTest.testFlush() {
        Estate obj = dod.getRandomEstate();
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estate' failed to provide an identifier", id);
        obj = estateService.findEstate(id);
        Assert.assertNotNull("Find method for 'Estate' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstate(obj);
        Integer currentVersion = obj.getVersion();
        estateRepository.flush();
        Assert.assertTrue("Version for 'Estate' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstateIntegrationTest.testUpdateEstateUpdate() {
        Estate obj = dod.getRandomEstate();
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estate' failed to provide an identifier", id);
        obj = estateService.findEstate(id);
        boolean modified =  dod.modifyEstate(obj);
        Integer currentVersion = obj.getVersion();
        Estate merged = estateService.updateEstate(obj);
        estateRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Estate' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstateIntegrationTest.testSaveEstate() {
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", dod.getRandomEstate());
        Estate obj = dod.getNewTransientEstate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Estate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Estate' identifier to be null", obj.getId());
        try {
            estateService.saveEstate(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        estateRepository.flush();
        Assert.assertNotNull("Expected 'Estate' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EstateIntegrationTest.testDeleteEstate() {
        Estate obj = dod.getRandomEstate();
        Assert.assertNotNull("Data on demand for 'Estate' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estate' failed to provide an identifier", id);
        obj = estateService.findEstate(id);
        estateService.deleteEstate(obj);
        estateRepository.flush();
        Assert.assertNull("Failed to remove 'Estate' with identifier '" + id + "'", estateService.findEstate(id));
    }
    
}
