// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.howed.heirshare5.domain;

import com.howed.heirshare5.domain.InventoryItemDataOnDemand;
import com.howed.heirshare5.domain.InventoryItemIntegrationTest;
import com.howed.heirshare5.repository.InventoryItemRepository;
import com.howed.heirshare5.service.InventoryItemService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InventoryItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InventoryItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InventoryItemIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InventoryItemIntegrationTest: @Transactional;
    
    @Autowired
    InventoryItemDataOnDemand InventoryItemIntegrationTest.dod;
    
    @Autowired
    InventoryItemService InventoryItemIntegrationTest.inventoryItemService;
    
    @Autowired
    InventoryItemRepository InventoryItemIntegrationTest.inventoryItemRepository;
    
    @Test
    public void InventoryItemIntegrationTest.testCountAllInventoryItems() {
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", dod.getRandomInventoryItem());
        long count = inventoryItemService.countAllInventoryItems();
        Assert.assertTrue("Counter for 'InventoryItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InventoryItemIntegrationTest.testFindInventoryItem() {
        InventoryItem obj = dod.getRandomInventoryItem();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to provide an identifier", id);
        obj = inventoryItemService.findInventoryItem(id);
        Assert.assertNotNull("Find method for 'InventoryItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'InventoryItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InventoryItemIntegrationTest.testFindAllInventoryItems() {
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", dod.getRandomInventoryItem());
        long count = inventoryItemService.countAllInventoryItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'InventoryItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<InventoryItem> result = inventoryItemService.findAllInventoryItems();
        Assert.assertNotNull("Find all method for 'InventoryItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'InventoryItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InventoryItemIntegrationTest.testFindInventoryItemEntries() {
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", dod.getRandomInventoryItem());
        long count = inventoryItemService.countAllInventoryItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<InventoryItem> result = inventoryItemService.findInventoryItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'InventoryItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'InventoryItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InventoryItemIntegrationTest.testFlush() {
        InventoryItem obj = dod.getRandomInventoryItem();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to provide an identifier", id);
        obj = inventoryItemService.findInventoryItem(id);
        Assert.assertNotNull("Find method for 'InventoryItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInventoryItem(obj);
        Integer currentVersion = obj.getVersion();
        inventoryItemRepository.flush();
        Assert.assertTrue("Version for 'InventoryItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InventoryItemIntegrationTest.testUpdateInventoryItemUpdate() {
        InventoryItem obj = dod.getRandomInventoryItem();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to provide an identifier", id);
        obj = inventoryItemService.findInventoryItem(id);
        boolean modified =  dod.modifyInventoryItem(obj);
        Integer currentVersion = obj.getVersion();
        InventoryItem merged = inventoryItemService.updateInventoryItem(obj);
        inventoryItemRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'InventoryItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InventoryItemIntegrationTest.testSaveInventoryItem() {
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", dod.getRandomInventoryItem());
        InventoryItem obj = dod.getNewTransientInventoryItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'InventoryItem' identifier to be null", obj.getId());
        try {
            inventoryItemService.saveInventoryItem(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        inventoryItemRepository.flush();
        Assert.assertNotNull("Expected 'InventoryItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InventoryItemIntegrationTest.testDeleteInventoryItem() {
        InventoryItem obj = dod.getRandomInventoryItem();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'InventoryItem' failed to provide an identifier", id);
        obj = inventoryItemService.findInventoryItem(id);
        inventoryItemService.deleteInventoryItem(obj);
        inventoryItemRepository.flush();
        Assert.assertNull("Failed to remove 'InventoryItem' with identifier '" + id + "'", inventoryItemService.findInventoryItem(id));
    }
    
}
